export const GET_NOTES = "GET_NOTES"
export const POST_NOTES= "POST_USER"
export const DELETE_NOTES = "DELETE_NOTES"
export const CHANGE_NOTES= "CHANGE_NOTES"

export const GET_CATEGORIES = "GET_CATEGORIES"
export const POST_CATEGORY= "POST_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"

export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY"
export const CHANGE_FILTER = "CHANGE_FILTER"
export const CHANGE_NOFILTER = "CHANGE_NOFILTER"



